name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  # What's Changed
  $CHANGES
categories:
  - title: "Breaking"
    label: "type: breaking"
  - title: "New"
    label: "type: feature"
  - title: "Bug Fixes"
    label: "type: bug"
  - title: "Testing"
    label: "type: tests"
  - title: "Maintenance"
    label: "type: maintenance"
  - title: "Documentation"
    label: "type: docs"
  - title: "Dependency Updates"
    label: "type: dependencies"

version-resolver:
  major:
    labels:
      - "type: breaking"
      - "major"
  minor:
    labels:
      - "type: feature"
      - "minor"
  patch:
    labels:
      - "type: bug"
      - "type: maintenance"
      - "type: docs"
      - "type: dependencies"
      - "type: security"
      - "patch"
      - "type: tests"
exclude-labels:
  - "skip ci"
