name: CI Cron

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */3 * *"

jobs:
  build:
    name: Build All
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run build
        run: make build-all

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[skip ci] Updated schemas'
          commit_user_name: Abhimanyu Saharan
          commit_user_email: desk.abhimanyu@gmail.com
          commit_author: Abhimanyu Saharan <desk.abhimanyu@gmail.com>
